services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-project-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www
      - ./php_ini/php.ini:/usr/local/etc/php/php.ini

  nginx:
    image: nginx:1.27.2-alpine
    container_name: php-project-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
    - ../:/var/www
    - ./nginx:/etc/nginx/conf.d

  db:
    image: mysql:8.0
    container_name: php-project-db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./storage/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

