services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-project-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www

  nginx:
    image: nginx:1.27.2-alpine
    container_name: php-project-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
    - ../src:/var/www
    - ./nginx:/etc/nginx/conf.d
